---
title: "Peak Detection"
output: html_notebook
---


```{r}
filter(tAllQ, HY == "1912") -> tHY1912
summary(tHY1912)
```

```{r}
plot(tHY1912$YMD, tHY1912$Q,"l" )
```
```{r}
lenYr <- dim(tHY1912)[1]

strideKernel <- function(inHYDF,DoY){
  # three day symmetric stride
  lenYr <- dim(inHYDF)
  stride <- 3
  startD <- inHYDF$YMD[1]
  header <- inHYDF[0,]
  footer <- inHYDF[0,]
  for (i in seq(1:strid)){
    
  }
  
  return(outDF)
}

mountainClimber <- function(inHYDF, DoY){
  lenYr <- dim(inHYDF)[1]
  k <- DoY
  # start at arbitrary point
  while(k > 0){
    outPut <- pickSteeper(inHYDF, k)
    k <- outPut[1]
    DoY <- k
    print(outPut)
  }
  return(DoY)
}

pickSteeper <- function(inHYDF,DoY){
  thisVal <- inHYDF$Q[DoY]
  rightVal <- inHYDF$Q[DoY+1]
  leftVal <- inHYDF$Q[DoY-1]
  if(rightVal > thisVal){return( c(DoY+1, rightVal) )}
  else if (leftVal > thisVal){return( c(DoY-1, leftVal))}
  else {return(c(0, thisVal))}
}

#mountainClimber(tHY1912, 20)
set.seed(123)
```

```{r}
set.seed(123)
spikes <- matrix(runif(200), ncol=2)
spikes[40, 1] <- 300
spikes[50, 2] <- 40
```



































